Documentation:
  Enabled: false

StringLiterals:
  Enabled: false

EmptyLinesAroundBody:
  Enabled: false

HashSyntax:
  Enabled: false

LineLength:
  Max: 100

SpaceInsideHashLiteralBraces:
  Enabled: false
